export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="lambda"

plugins=(git common-aliases docker sudo zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_USE_ASYNC=1
TERM=xterm-256color

test -r "~/.dir_colors" && eval $(dircolors ~/.dir_colors)
